server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

spring:
  application:
    name: spring-cloud-gateway
  cloud:
#    discovery:
#      reactive:
#        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: body_read
          uri: lb://eureka-client
          predicates:
            - After=2020-04-20T00:00:00+08:00[Asia/Shanghai]